### ISSUE TITLE
Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v50-tier1-team-03#5]
**__Task Description__**
- [x] Using everyone's availability posted to [When2Meet](https://www.when2meet.com/) schedule a Kickoff meeting
- [x] Use the [Kickoff meeting template](https://docs.google.com/document/d/1ozP5lLj_R0kqCWdXEpFDR6sIlP9miXp74DFKZlJyktE/edit?usp=sharing) in the shared document directory we've provided to guide the discussion and to record notes, decisions, and assignments
- [x] Set a time for your next meeting for later in the week

**__Technical Considerations__**
N/a

**__Additional Considerations__**
N/a

**__Resources__**
[Conduct Kickoff Meeting (Chingu Handbook)](https://github.com/chingu-voyages/Handbook/blob/main/docs/guides/voyage/voyage.md#2-conduct-kickoff-meeting)

**Member of Epic:** #16

**Comment by Mikelovin23** [comment]
when2meet link for KO: https://www.when2meet.com/?25480006-hLJYm

<img width="981" alt="SCR-20240701-qofl" src="https://github.com/chingu-voyages/v50-tier1-team-03/assets/161270515/be83f318-bff1-4bc9-a724-836d4b06f051">
